import { useState } from 'react';
import { Alert, Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { ScreenContainer } from '@/components/screen-container';
import { PrimaryButton, SecondaryButton, StatusPill } from '@/components/app-ui';
import { expenses, formatCurrency } from '@/lib/demo-data';
import { IconSymbol } from '@/components/ui/icon-symbol';
import { useColors } from '@/hooks/use-colors';

export default function ExpensesScreen() {
  const colors = useColors(); const [showForm, setShowForm] = useState(false); const [amount, setAmount] = useState('');
  if (showForm) return <NewExpense onCancel={() => setShowForm(false)} onSaved={() => { setShowForm(false); Alert.alert('Despesa adicionada', 'O lançamento foi salvo no rascunho da prestação.'); }} amount={amount} setAmount={setAmount} />;
  const total = expenses.reduce((sum, expense) => sum + expense.quantity * expense.unitValue, 0);
  return <ScreenContainer edges={['top', 'bottom', 'left', 'right']} className="px-5 pt-4"><Pressable onPress={() => router.back()} className="mb-5"><Text className="font-semibold text-primary">‹ Voltar</Text></Pressable><View className="flex-row items-end justify-between"><View><Text className="text-sm font-medium text-muted">TR-2026-031 · Ciudad del Este</Text><Text className="mt-1 text-3xl font-bold text-foreground">Despesas</Text></View><Pressable onPress={() => setShowForm(true)} style={({ pressed }) => [{ backgroundColor: colors.primary, opacity: pressed ? 0.75 : 1 }]} className="h-11 w-11 items-center justify-center rounded-2xl"><IconSymbol name="plus" size={22} color="white" /></Pressable></View><View className="mt-6 flex-row gap-3"><View className="flex-1 rounded-2xl border border-border bg-surface p-4"><Text className="text-xs text-muted">Total lançado</Text><Text className="mt-2 text-xl font-bold text-foreground">{formatCurrency(total)}</Text></View><View className="flex-1 rounded-2xl border border-border bg-surface p-4"><Text className="text-xs text-muted">Itens pendentes</Text><Text className="mt-2 text-xl font-bold text-warning">01</Text></View></View><Text className="mb-3 mt-8 text-base font-bold text-foreground">Lançamentos recentes</Text><View className="gap-3">{expenses.map((expense) => { const lineTotal = expense.quantity * expense.unitValue; const overLimit = lineTotal > expense.limit; return <View key={expense.id} className="rounded-2xl border border-border bg-surface p-4"><View className="flex-row items-start"><View className="flex-1"><Text className="text-xs text-muted">{expense.date} · {expense.city}</Text><Text className="mt-1 font-bold text-foreground">{expense.concept}</Text><Text className="mt-1 text-xs text-muted">{expense.client} · {expense.quantity} × {formatCurrency(expense.unitValue)}</Text></View><Text className="font-bold text-foreground">{formatCurrency(lineTotal)}</Text></View><View className="mt-3 flex-row items-center"><StatusPill status={overLimit ? 'Revisão necessária' : 'Pronto para envio'} /><Text className="ml-auto text-xs text-muted">{expense.prepaid ? 'Adiantado' : 'Administrativo'}</Text></View>{expense.reviewNote ? <Text className="mt-3 rounded-xl bg-warning/10 p-3 text-xs leading-4 text-warning">Observação: {expense.reviewNote}</Text> : null}</View>; })}</View><View className="mt-6"><PrimaryButton label="Enviar fechamento" onPress={() => Alert.alert('Fechamento enviado', 'O administrativo foi notificado para revisar os lançamentos.')} /><View className="mt-2"><SecondaryButton label="Adicionar outro lançamento" onPress={() => setShowForm(true)} /></View></View></ScreenContainer>;
}

function NewExpense({ onCancel, onSaved, amount, setAmount }: { onCancel: () => void; onSaved: () => void; amount: string; setAmount: (value: string) => void }) { const colors = useColors(); return <ScreenContainer edges={['top', 'bottom', 'left', 'right']} className="px-5 pt-4"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{ paddingBottom: 30 }}><Pressable onPress={onCancel} className="mb-5"><Text className="font-semibold text-primary">‹ Voltar para despesas</Text></Pressable><Text className="text-3xl font-bold text-foreground">Nova despesa</Text><Text className="mt-2 text-sm leading-5 text-muted">Anexe o comprovante para manter a prestação pronta para revisão.</Text><Label text="Conceito do gasto" /><Select value="Alimentação" /><Label text="Cidade do atendimento" /><Select value="Ciudad del Este" /><Label text="Cliente" /><Select value="AgroNorte S.A." /><View className="flex-row gap-3"><View className="flex-1"><Label text="Quantidade" /><TextInput defaultValue="1" keyboardType="numeric" placeholderTextColor={colors.muted} className="rounded-2xl border border-border bg-surface px-4 py-4 text-foreground" /></View><View className="flex-1"><Label text="Valor unitário" /><TextInput value={amount} onChangeText={setAmount} keyboardType="decimal-pad" placeholder="0,00" placeholderTextColor={colors.muted} className="rounded-2xl border border-border bg-surface px-4 py-4 text-foreground" /></View></View><Label text="Comprovante" /><Pressable onPress={() => Alert.alert('Selecionar comprovante', 'Na integração nativa, este botão abrirá câmera/galeria e comprimirá imagens, incluindo HEIC, antes do upload.')} style={({ pressed }) => [{ borderColor: colors.primary, opacity: pressed ? 0.7 : 1 }]} className="flex-row items-center rounded-2xl border border-dashed bg-surface p-5"><View style={{ backgroundColor: `${colors.primary}18` }} className="h-11 w-11 items-center justify-center rounded-xl"><IconSymbol name="camera.fill" size={22} color={colors.primary} /></View><View className="ml-3"><Text className="font-bold text-foreground">Adicionar foto ou fatura</Text><Text className="mt-1 text-xs text-muted">JPG, PNG, PDF ou HEIC</Text></View></Pressable><Label text="Pagamento" /><Select value="Pago com adiantamento" /><View className="mt-6"><PrimaryButton label="Salvar despesa" onPress={onSaved} /></View></ScrollView></ScreenContainer>; }
function Label({ text }: { text: string }) { return <Text className="mb-2 mt-5 text-sm font-bold text-foreground">{text}</Text>; }
function Select({ value }: { value: string }) { const colors = useColors(); return <View className="flex-row items-center rounded-2xl border border-border bg-surface px-4 py-4"><Text className="flex-1 text-foreground">{value}</Text><Text style={{ color: colors.primary }} className="text-lg">⌄</Text></View>; }
