import { Alert, Pressable, ScrollView, Text, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { useState } from 'react';
import { ScreenContainer } from '@/components/screen-container';
import { PrimaryButton, SectionHeader, StatusPill } from '@/components/app-ui';
import { fleetReservations, trips, units, vehicles } from '@/lib/demo-data';
import { IconSymbol } from '@/components/ui/icon-symbol';
import { useColors } from '@/hooks/use-colors';

export default function FleetReservationScreen() {
  const colors = useColors();
  const params = useLocalSearchParams<{ reservationId?: string }>();
  const reservation = fleetReservations.find((item) => item.id === params.reservationId) ?? fleetReservations.find((item) => item.status === 'Aguardando veículo');
  const trip = trips.find((item) => item.id === reservation?.tripId);
  const [selectedId, setSelectedId] = useState<string>();
  const availableVehicles = vehicles.filter((vehicle) => vehicle.status === 'Disponível');
  const confirm = () => { if (!selectedId) { Alert.alert('Selecione um veículo', 'Escolha um veículo disponível para vincular à viagem.'); return; } Alert.alert('Reserva confirmada', `${vehicles.find((vehicle) => vehicle.id === selectedId)?.plate} foi reservado para ${trip?.destination}.`, [{ text: 'Voltar para Frota', onPress: () => router.replace('/fleet') }]); };
  return <ScreenContainer edges={['top', 'bottom', 'left', 'right']} className="px-5 pt-4"><View className="w-full max-w-4xl flex-1 self-center"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{ paddingBottom: 36 }}><Pressable onPress={() => router.back()} className="mb-5"><Text className="font-semibold text-primary">‹ Voltar para Frota</Text></Pressable><Text className="text-sm font-medium text-muted">Administrativo · Reserva de frota</Text><Text className="mt-1 text-3xl font-bold text-foreground">Associar veículo</Text><Text className="mt-2 text-sm leading-5 text-muted">Use os dados da viagem aberta para reservar um veículo disponível e confirmar o condutor.</Text><SectionHeader title="Viagem solicitante" /><View className="rounded-2xl border border-border bg-surface p-5"><View className="flex-row items-start justify-between"><View><Text className="text-xs font-bold tracking-wider text-muted">{trip?.id} · {reservation?.id}</Text><Text className="mt-2 text-xl font-bold text-foreground">{trip?.destination}</Text><Text className="mt-1 text-sm text-muted">{reservation?.startDate} — {reservation?.endDate} · Condutor: {reservation?.driver}</Text></View><StatusPill status="Aguardando veículo" /></View></View><SectionHeader title="Veículos disponíveis" action={`${availableVehicles.length} opções`} />{availableVehicles.map((vehicle) => { const unit = units.find((unitItem) => unitItem.id === vehicle.unitId); const selected = selectedId === vehicle.id; return <Pressable key={vehicle.id} onPress={() => setSelectedId(vehicle.id)} style={{ borderColor: selected ? colors.primary : colors.border, backgroundColor: selected ? `${colors.primary}10` : colors.surface }} className="mb-3 rounded-2xl border p-5"><View className="flex-row items-center"><View style={{ backgroundColor: selected ? colors.primary : `${colors.primary}16` }} className="h-11 w-11 items-center justify-center rounded-xl"><IconSymbol name="car.fill" size={22} color={selected ? 'white' : colors.primary} /></View><View className="ml-3 flex-1"><Text className="font-bold text-foreground">{vehicle.brand} {vehicle.model}</Text><Text className="mt-1 text-sm text-muted">{vehicle.plate} · {vehicle.year} · {unit?.name}</Text><Text className="mt-1 text-xs text-muted">{vehicle.currentKm.toLocaleString('pt-BR')} km · Extintor {vehicle.extinguisherDue}</Text></View><View style={{ borderColor: selected ? colors.primary : colors.border, backgroundColor: selected ? colors.primary : 'transparent' }} className="h-6 w-6 items-center justify-center rounded-full border">{selected ? <IconSymbol name="checkmark" size={14} color="white" /> : null}</View></View></Pressable>; })}<PrimaryButton label="Confirmar reserva" onPress={confirm} /></ScrollView></View></ScreenContainer>;
}
