import { useMemo, useState } from 'react';
import { Pressable, ScrollView, Text, View } from 'react-native';
import { router } from 'expo-router';
import { ScreenContainer } from '@/components/screen-container';
import { formatCurrency, fleetWorkOrders, maintenanceReasons, vehicles } from '@/lib/demo-data';
import { useColors } from '@/hooks/use-colors';

export default function MaintenanceReportScreen() {
  const colors = useColors();
  const [vehicleId, setVehicleId] = useState('Todos');
  const [period, setPeriod] = useState('2026');
  const filtered = useMemo(() => fleetWorkOrders.filter((order) => vehicleId === 'Todos' || order.vehicleId === vehicleId), [vehicleId]);
  const total = filtered.reduce((sum, order) => sum + order.cost, 0);
  const preventive = filtered.filter((order) => order.kind === 'Preventiva').reduce((sum, order) => sum + order.cost, 0);
  const corrective = filtered.filter((order) => order.kind === 'Corretiva').reduce((sum, order) => sum + order.cost, 0);
  return <ScreenContainer edges={['top', 'bottom', 'left', 'right']} className="px-5 pt-4"><View className="w-full max-w-6xl flex-1 self-center"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{ paddingBottom: 40 }}><Pressable onPress={() => router.back()}><Text className="mb-5 font-semibold text-primary">‹ Voltar para Frota</Text></Pressable><Text className="text-sm font-medium text-muted">Administrativo · Análise financeira</Text><Text className="mt-1 text-3xl font-bold text-foreground">Relatório de manutenções</Text><Text className="mt-2 text-sm leading-5 text-muted">Avalie gastos realizados por veículo, período e tipo de manutenção.</Text><View className="mt-6 rounded-2xl border border-border bg-surface p-4"><Text className="mb-2 text-xs font-bold uppercase tracking-widest text-muted">Filtros do relatório</Text><Text className="mb-2 mt-2 text-xs font-semibold text-muted">Veículo</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 8 }}>{['Todos', ...vehicles.map((vehicle) => vehicle.id)].map((id) => <FilterChip key={id} label={id === 'Todos' ? 'Todos' : vehicles.find((vehicle) => vehicle.id === id)?.plate ?? id} selected={vehicleId === id} onPress={() => setVehicleId(id)} />)}</ScrollView><Text className="mb-2 mt-4 text-xs font-semibold text-muted">Período</Text><View className="flex-row gap-2"><FilterChip label="2026" selected={period === '2026'} onPress={() => setPeriod('2026')} /><FilterChip label="Últimos 90 dias" selected={period === '90'} onPress={() => setPeriod('90')} /></View></View><View className="mt-6 flex-row gap-3"><Summary label="Total" value={formatCurrency(total)} color={colors.primary} /><Summary label="Preventiva" value={formatCurrency(preventive)} color={colors.success} /><Summary label="Corretiva" value={formatCurrency(corrective)} color={colors.warning} /></View><Text className="mb-3 mt-8 text-base font-bold text-foreground">Manutenções realizadas · {period === '2026' ? 'Ano 2026' : 'Últimos 90 dias'}</Text><View className="rounded-2xl border border-border bg-surface p-2">{filtered.map((order) => { const vehicle = vehicles.find((item) => item.id === order.vehicleId); const reason = maintenanceReasons.find((item) => item.id === order.reasonId); return <View key={order.id} className="border-b border-border p-4 last:border-b-0"><View className="flex-row items-start justify-between"><View className="flex-1"><Text className="text-xs font-bold tracking-wider text-muted">{order.id} · {order.maintenanceDate}</Text><Text className="mt-1 font-bold text-foreground">{vehicle?.brand} {vehicle?.model} · {vehicle?.plate}</Text><Text className="mt-1 text-sm text-muted">{order.kind} · {reason?.name}</Text></View><Text className="font-bold text-foreground">{formatCurrency(order.cost)}</Text></View><Text className="mt-2 text-xs text-muted">KM {order.km.toLocaleString('pt-BR')} · {order.observation}</Text></View>; })}</View></ScrollView></View></ScreenContainer>;
}
function FilterChip({ label, selected, onPress }: { label: string; selected: boolean; onPress: () => void }) { const colors = useColors(); return <Pressable onPress={onPress} style={{ backgroundColor: selected ? colors.primary : colors.background, borderColor: selected ? colors.primary : colors.border }} className="rounded-xl border px-3 py-2"><Text style={{ color: selected ? '#fff' : colors.foreground }} className="text-xs font-bold">{label}</Text></Pressable>; }
function Summary({ label, value, color }: { label: string; value: string; color: string }) { return <View className="flex-1 rounded-2xl border border-border bg-surface p-4"><Text className="text-xs text-muted">{label}</Text><Text style={{ color }} className="mt-2 text-lg font-bold">{value}</Text></View>; }
