import { ScrollView, Text, View } from 'react-native';
import { router } from 'expo-router';
import { ScreenContainer } from '@/components/screen-container';
import { MetricCard, SectionHeader } from '@/components/app-ui';
import { expenses, formatCurrency } from '@/lib/demo-data';
import { IconSymbol } from '@/components/ui/icon-symbol';
import { useColors } from '@/hooks/use-colors';

export default function ReportsScreen() {
  const colors = useColors(); const total = expenses.reduce((sum, expense) => sum + expense.quantity * expense.unitValue, 0); const billable = expenses.filter((expense) => expense.billable).reduce((sum, expense) => sum + expense.quantity * expense.unitValue, 0);
  return <ScreenContainer edges={['top', 'bottom', 'left', 'right']} className="px-5 pt-4"><View className="w-full max-w-6xl flex-1 self-center"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{ paddingBottom: 36 }}><Text onPress={() => router.back()} className="mb-5 font-semibold text-primary">‹ Voltar</Text><Text className="text-sm font-medium text-muted">Administrativo · Agosto 2026</Text><Text className="mt-1 text-3xl font-bold text-foreground">Relatórios</Text><Text className="mt-2 text-sm leading-5 text-muted">Acompanhe limites, faturamento e composição das despesas por cliente.</Text><View className="mt-6 flex-row gap-3"><MetricCard label="Despesas" value={formatCurrency(total)} accent={colors.primary} /><MetricCard label="Faturável" value={formatCurrency(billable)} accent={colors.success} /></View><SectionHeader title="Resumo por cliente" /><View className="rounded-2xl border border-border bg-surface p-5"><SummaryRow client="AgroNorte S.A." concept="Viáticos" value="R$ 36,00" color={colors.primary} /><SummaryRow client="AgroNorte S.A." concept="Quilometragem" value="R$ 32,00" color={colors.success} /><SummaryRow client="AgroNorte S.A." concept="Hospedagem" value="R$ 86,00" color={colors.warning} /></View><SectionHeader title="Relatório analítico" /><View className="overflow-hidden rounded-2xl border border-border bg-surface"><View className="flex-row bg-background px-4 py-3"><Text className="w-[28%] text-[10px] font-bold uppercase text-muted">Data / Cidade</Text><Text className="w-[28%] text-[10px] font-bold uppercase text-muted">Conceito</Text><Text className="w-[22%] text-[10px] font-bold uppercase text-muted">Total</Text><Text className="w-[22%] text-[10px] font-bold uppercase text-muted">Limite</Text></View>{expenses.map((expense) => { const value = expense.quantity * expense.unitValue; return <View key={expense.id} className="flex-row border-t border-border px-4 py-4"><View className="w-[28%]"><Text className="text-xs font-semibold text-foreground">{expense.date}</Text><Text className="mt-1 text-[10px] text-muted">{expense.city}</Text></View><Text className="w-[28%] text-xs text-foreground">{expense.concept}</Text><Text className="w-[22%] text-xs font-bold text-foreground">{formatCurrency(value)}</Text><Text style={{ color: value > expense.limit ? colors.error : colors.success }} className="w-[22%] text-xs font-semibold">{value > expense.limit ? `+${formatCurrency(value - expense.limit)}` : 'Dentro'}</Text></View>; })}</View><View className="mt-5 flex-row items-center rounded-2xl border border-primary/20 bg-primary/10 p-4"><IconSymbol name="chart.bar.fill" size={20} color={colors.primary} /><Text className="ml-3 flex-1 text-sm leading-5 text-foreground">Os dados podem ser exportados para o ERP após o fechamento administrativo.</Text></View></ScrollView></View></ScreenContainer>;
}
function SummaryRow({ client, concept, value, color }: { client: string; concept: string; value: string; color: string }) { return <View className="mb-4 flex-row items-center"><View style={{ backgroundColor: `${color}22` }} className="h-9 w-9 items-center justify-center rounded-xl"><IconSymbol name="wallet.pass.fill" size={17} color={color} /></View><View className="ml-3 flex-1"><Text className="text-sm font-bold text-foreground">{client}</Text><Text className="mt-1 text-xs text-muted">{concept}</Text></View><Text className="font-bold text-foreground">{value}</Text></View>; }
