import { Alert, Pressable, ScrollView, Text, View } from 'react-native';
import { router } from 'expo-router';
import { ScreenContainer } from '@/components/screen-container';
import { PrimaryButton, SectionHeader, StatusPill } from '@/components/app-ui';
import { expenses, formatCurrency, trips } from '@/lib/demo-data';
import { IconSymbol } from '@/components/ui/icon-symbol';
import { useColors } from '@/hooks/use-colors';

export default function TripDetailScreen() {
  const trip = trips[0]; const tripExpenses = expenses.filter((expense) => expense.tripId === trip.id); const spent = tripExpenses.reduce((sum, expense) => sum + expense.quantity * expense.unitValue, 0);
  return <ScreenContainer edges={['top', 'bottom', 'left', 'right']} className="px-5 pt-4"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{ paddingBottom: 32 }}><Pressable onPress={() => router.back()} className="mb-5"><Text className="font-semibold text-primary">‹ Voltar</Text></Pressable><View className="flex-row items-start justify-between"><View><Text className="text-xs font-bold tracking-wider text-muted">{trip.id}</Text><Text className="mt-2 text-3xl font-bold text-foreground">{trip.destination}</Text><Text className="mt-1 text-sm text-muted">{trip.startDate} — {trip.endDate} · {trip.client}</Text></View><StatusPill status={trip.status} /></View><View className="mt-6 flex-row gap-3"><View className="flex-1 rounded-2xl border border-border bg-surface p-4"><Text className="text-xs text-muted">Adiantamento</Text><Text className="mt-2 text-lg font-bold text-foreground">{formatCurrency(trip.amount)}</Text></View><View className="flex-1 rounded-2xl border border-border bg-surface p-4"><Text className="text-xs text-muted">Despesas lançadas</Text><Text className="mt-2 text-lg font-bold text-primary">{formatCurrency(spent)}</Text></View></View><SectionHeader title="Linha do tempo" /><View className="rounded-2xl border border-border bg-surface p-5"><TimelineItem title="Solicitação criada" detail="12 ago · Viajante" done /><TimelineItem title="Aprovada pela área" detail="13 ago · Carlos Mendes" done /><TimelineItem title="Liberada para viagem" detail="17 ago · Administrativo" done /><TimelineItem title="Prestação de contas" detail="Em andamento" done={false} last /></View><SectionHeader title="Dados operacionais" /><View className="rounded-2xl border border-border bg-surface p-5"><Info label="Área" value={trip.area} /><Info label="Transporte" value={trip.transport} /><Info label="Hospedagem" value={trip.needsHotel ? 'Necessária' : 'Não necessária'} /><Info label="Cliente faturável" value="Sim, conforme vínculo" /></View><SectionHeader title="Despesas" action={`${tripExpenses.length} itens`} /><PrimaryButton label="Adicionar despesa" onPress={() => router.push('/expenses')} /><Pressable onPress={() => Alert.alert('Fechamento enviado', 'O administrativo receberá os comprovantes para revisão.')} style={({ pressed }) => [{ opacity: pressed ? 0.7 : 1 }]} className="mt-3 items-center py-3"><Text className="font-bold text-primary">Enviar fechamento para o Administrativo</Text></Pressable></ScrollView></ScreenContainer>;
}
function TimelineItem({ title, detail, done, last }: { title: string; detail: string; done: boolean; last?: boolean }) { const colors = useColors(); return <View className="flex-row"><View className="items-center"><View style={{ backgroundColor: done ? colors.success : colors.background, borderColor: done ? colors.success : colors.border }} className="h-6 w-6 items-center justify-center rounded-full border">{done ? <IconSymbol name="checkmark" size={14} color="white" /> : null}</View>{!last ? <View style={{ backgroundColor: colors.border }} className="h-9 w-px" /> : null}</View><View className="ml-3 pb-3"><Text className="font-bold text-foreground">{title}</Text><Text className="mt-1 text-xs text-muted">{detail}</Text></View></View>; }
function Info({ label, value }: { label: string; value: string }) { return <View className="mb-3 flex-row justify-between"><Text className="text-sm text-muted">{label}</Text><Text className="max-w-[58%] text-right text-sm font-semibold text-foreground">{value}</Text></View>; }
