import { useState } from 'react';
import { Alert, FlatList, Pressable, Text, View } from 'react-native';
import { ScreenContainer } from '@/components/screen-container';
import { adminQueue } from '@/lib/demo-data';
import { IconSymbol } from '@/components/ui/icon-symbol';
import { useColors } from '@/hooks/use-colors';

export default function OperationsScreen() {
  const colors = useColors();
  const [released, setReleased] = useState<string[]>([]);
  return <ScreenContainer className="px-5 pt-4"><Text className="text-sm font-medium text-muted">Backoffice de viagens</Text><Text className="mt-1 text-3xl font-bold text-foreground">Operação</Text><View className="mt-5 flex-row gap-3"><View className="flex-1 rounded-2xl border border-border bg-surface p-4"><Text className="text-xs text-muted">Aguardando ação</Text><Text className="mt-2 text-2xl font-bold text-warning">{adminQueue.length - released.length}</Text></View><View className="flex-1 rounded-2xl border border-border bg-surface p-4"><Text className="text-xs text-muted">Liberadas hoje</Text><Text className="mt-2 text-2xl font-bold text-success">{released.length}</Text></View></View><FlatList className="mt-6" data={adminQueue} keyExtractor={(item) => item.id} contentContainerStyle={{ paddingBottom: 36, gap: 12 }} renderItem={({ item }) => { const isReleased = released.includes(item.id); return <View className="rounded-3xl border border-border bg-surface p-5"><View className="flex-row items-start"><View className="flex-1"><Text className="text-xs font-bold tracking-wider text-muted">{item.id}</Text><Text className="mt-2 text-lg font-bold text-foreground">{item.destination}</Text><Text className="mt-1 text-sm text-muted">{item.traveler}</Text></View><View style={{ backgroundColor: isReleased ? `${colors.success}22` : `${colors.warning}22` }} className="rounded-full px-3 py-1"><Text style={{ color: isReleased ? colors.success : colors.warning }} className="text-xs font-bold">{isReleased ? 'Liberada' : item.status}</Text></View></View><View className="mt-5 gap-3"><CheckRow label="Adiantamento ao viajante" done={isReleased} /><CheckRow label="Reserva de hotel" done={isReleased || !item.hotel} /><CheckRow label="Alocação de veículo" done={isReleased || !item.vehicle} /></View><Pressable onPress={() => { setReleased((current) => current.includes(item.id) ? current : [...current, item.id]); Alert.alert('Viagem liberada', 'O viajante já pode iniciar o deslocamento e lançar despesas.'); }} disabled={isReleased} style={({ pressed }) => [{ backgroundColor: isReleased ? colors.border : colors.primary, opacity: pressed ? 0.75 : 1 }]} className="mt-5 items-center rounded-xl px-4 py-3"><Text className="font-bold text-white">{isReleased ? 'Preparação concluída' : 'Liberar para viagem'}</Text></Pressable></View>; }} /> </ScreenContainer>;
}

function CheckRow({ label, done }: { label: string; done: boolean }) { const colors = useColors(); return <View className="flex-row items-center"><View style={{ backgroundColor: done ? colors.success : colors.background, borderColor: done ? colors.success : colors.border }} className="h-5 w-5 items-center justify-center rounded-md border">{done ? <IconSymbol name="checkmark" size={14} color="white" /> : null}</View><Text className="ml-3 text-sm text-foreground">{label}</Text></View>; }
