import { Alert, Pressable, ScrollView, Text, View } from 'react-native';
import { ScreenContainer } from '@/components/screen-container';
import { demoUser } from '@/lib/demo-data';
import { IconSymbol } from '@/components/ui/icon-symbol';
import { useColors } from '@/hooks/use-colors';

export default function ProfileScreen() {
  const colors = useColors();
  return <ScreenContainer className="px-5 pt-4"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{ paddingBottom: 40 }}><Text className="text-sm font-medium text-muted">Conta e preferências</Text><Text className="mt-1 text-3xl font-bold text-foreground">Perfil</Text><View className="mt-6 flex-row items-center rounded-3xl border border-border bg-surface p-5"><View style={{ backgroundColor: `${colors.primary}18` }} className="h-14 w-14 items-center justify-center rounded-2xl"><Text className="text-xl font-bold text-primary">ML</Text></View><View className="ml-4 flex-1"><Text className="text-lg font-bold text-foreground">{demoUser.name}</Text><Text className="mt-1 text-sm text-muted">{demoUser.email}</Text><Text className="mt-1 text-xs font-semibold text-primary">Viajante · Aprovador</Text></View></View><Text className="mb-3 mt-8 text-base font-bold text-foreground">Preferências</Text><SettingRow icon="globe" label="Idioma" value="Português (Brasil)" /><SettingRow icon="moon.fill" label="Aparência" value="Automático" /><SettingRow icon="bell.fill" label="Notificações" value="Ativadas" /><Text className="mb-3 mt-8 text-base font-bold text-foreground">Acesso administrativo</Text><Pressable onPress={() => Alert.alert('Perfis disponíveis', 'A demonstração atual combina os perfis Viajante e Aprovador. O Administrativo possui painéis próprios de operação e relatórios.')} style={({ pressed }) => [{ opacity: pressed ? 0.7 : 1 }]} className="flex-row items-center rounded-2xl border border-border bg-surface p-4"><IconSymbol name="checkmark.seal.fill" size={22} color={colors.primary} /><View className="ml-3 flex-1"><Text className="font-bold text-foreground">Perfis e permissões</Text><Text className="mt-1 text-sm text-muted">Viajante e Aprovador ativos</Text></View><IconSymbol name="chevron.right" size={20} color={colors.muted} /></Pressable><Pressable onPress={() => Alert.alert('Sessão encerrada', 'Na integração final, o usuário será redirecionado para o acesso Supabase.')} style={({ pressed }) => [{ opacity: pressed ? 0.7 : 1 }]} className="mt-6 items-center rounded-2xl border border-error px-5 py-4"><Text className="font-bold text-error">Encerrar sessão</Text></Pressable></ScrollView></ScreenContainer>;
}

function SettingRow({ icon, label, value }: { icon: 'globe' | 'moon.fill' | 'bell.fill'; label: string; value: string }) { const colors = useColors(); return <View className="mb-2 flex-row items-center rounded-2xl border border-border bg-surface p-4"><IconSymbol name={icon} size={21} color={colors.primary} /><Text className="ml-3 flex-1 font-semibold text-foreground">{label}</Text><Text className="text-sm text-muted">{value}</Text><IconSymbol name="chevron.right" size={18} color={colors.muted} /></View>; }
